FROM ubuntu:latest

RUN apt-get upgrade && apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get -y install python3.10

RUN useradd -ms /bin/bash user
USER user
WORKDIR /home/user

CMD python3.10 --version
